//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBL.Resources.Views.Turnir {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Registracija {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registracija() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoBL.Resources.Views.Turnir.Registracija", typeof(Registracija).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pošalji ähnelt.
        /// </summary>
        public static string btnPosalji {
            get {
                return ResourceManager.GetString("btnPosalji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die *Datum rodjenja ähnelt.
        /// </summary>
        public static string lblDatumRodjenja {
            get {
                return ResourceManager.GetString("lblDatumRodjenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drzava ähnelt.
        /// </summary>
        public static string lblDrazava {
            get {
                return ResourceManager.GetString("lblDrazava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die **mail ähnelt.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ime ähnelt.
        /// </summary>
        public static string lblIme {
            get {
                return ResourceManager.GetString("lblIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorija ähnelt.
        /// </summary>
        public static string lblKategorija {
            get {
                return ResourceManager.GetString("lblKategorija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Klub ähnelt.
        /// </summary>
        public static string lblKlub {
            get {
                return ResourceManager.GetString("lblKlub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die *Napomena ähnelt.
        /// </summary>
        public static string lblNapomena {
            get {
                return ResourceManager.GetString("lblNapomena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die --Odaberi kategoriju-- ähnelt.
        /// </summary>
        public static string lblOdaberiKategoriju {
            get {
                return ResourceManager.GetString("lblOdaberiKategoriju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die * Ovi podaci se javno ne prikazuju ähnelt.
        /// </summary>
        public static string lblPodaciSeNePrikazuje {
            get {
                return ResourceManager.GetString("lblPodaciSeNePrikazuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prezime ähnelt.
        /// </summary>
        public static string lblPrezime {
            get {
                return ResourceManager.GetString("lblPrezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prijava za turnir ähnelt.
        /// </summary>
        public static string lblPrijavaZaTurnir {
            get {
                return ResourceManager.GetString("lblPrijavaZaTurnir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drzava je obavezna! ähnelt.
        /// </summary>
        public static string RequiredDrzava {
            get {
                return ResourceManager.GetString("RequiredDrzava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email je obavezan! ähnelt.
        /// </summary>
        public static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ime je obavezno! ähnelt.
        /// </summary>
        public static string RequiredIme {
            get {
                return ResourceManager.GetString("RequiredIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kategorija je obavezna! ähnelt.
        /// </summary>
        public static string RequiredKategorija {
            get {
                return ResourceManager.GetString("RequiredKategorija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Klub je obavezan! ähnelt.
        /// </summary>
        public static string RequiredKlub {
            get {
                return ResourceManager.GetString("RequiredKlub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prezime je obavezno! ähnelt.
        /// </summary>
        public static string RequiredPrezime {
            get {
                return ResourceManager.GetString("RequiredPrezime", resourceCulture);
            }
        }
    }
}
